160 refresh of docs + fixing of minor errors & typos
sylabs/singularity-userdocs pull request #161
Opened 2023-03-08 17:50 UTC by preminger

## Description of the Pull Request (PR):

Refreshing the docs, and fixing a collection of minor issues & typos encountered during @preminger's intake of the userdocs in winter 2023.

## This fixes or addresses the following GitHub issues:

- Fixes #160

2023-03-13 15:38 UTC, preminger commented
Ending this PR after updating only the following files; a separate Issue (and PR) will be opened for the remainder of the documentation.

- introduction.rst
- quick_start.rst
- security.rst
- definition_files.rst
- build_a_container.rst

2023-03-13 16:05 UTC, EmmEff approved these changes
A couple of minor suggested corrections... if you don't agree, just ignore them :)

2023-03-13 16:05 UTC, EmmEff commented on quick_start.rst
> +use the ``list`` command in the ``capability`` command group, like so:
You changed "like so" to "as follows" elsewhere, so should this as be changed to "as follows"?

2023-03-13 16:05 UTC, EmmEff commented on quick_start.rst
> +   instead.
This is not quite correct. If you pull a Docker image using "myimage@DIGEST" (as opposed to "myimage:TAG"), you'll always get the same image. Tags "map" to digests. Tags are mutable. Digests are not.

2023-03-13 16:05 UTC, EmmEff commented on quick_start.rst
> +Because {Singularity} runscripts are evaluated shell scripts arguments can
```suggestion
Because {Singularity} runscripts are evaluated shell scripts, arguments can
```

I think (?)

2023-03-13 16:11 UTC, dtrudg requested changes
Just a couple of very minor things. Thanks for these improvements!

2023-03-13 16:11 UTC, dtrudg commented on build_a_container.rst
> +Building with ``--remote``
Not sure about this title change, as what we are describing is a 'remote build', so perhaps the previous title fits better.

2023-03-13 16:11 UTC, dtrudg commented on build_a_container.rst
> +- Do not support ``arch`` / ``debootstrap`` / ``yum`` / ``zypper`` bootstraps. Use ``localimage``, ``library``, ``oras``, or one of the ``docker``/``oci`` sources.
Please wrap this line at 80 chars.

2023-03-13 16:11 UTC, dtrudg commented on quick_start.rst
> + Building images from scratch
Can remove the leading space here.

The most common way of writing an RST heading has the overline/underline *exactly* the same length as the title text.

Having the overline/underline 1 char before, and 1 char after the title test is from an outdated linting/formatting tool that was applied at some point.

2023-03-13 16:11 UTC, dtrudg commented on quick_start.rst
> + {Singularity} on a shared resource
As previous r.e. overline/underline/indent.

2023-03-13 16:11 UTC, dtrudg commented on security.rst
> +without ever decrypted its contents to disk.
```suggestion
without ever decrypting its contents to disk.
```

2023-03-13 16:20 UTC, preminger commented on build_a_container.rst
> +Building with ``--remote``
Yes, I agree with this. I was initially concerned that starting a header with a double-backticked flag would make the heading stick out & look unlike other headings, but then I saw that other headings in this document do the same thing, and never went back & reverted this change. Thanks!

2023-03-14 09:31 UTC, dtrudg approved these changes

2023-03-14 09:31 UTC, merged